name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.2+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Internationalizing
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Firebase Core Flutter SDK
  firebase_core: ^1.0.1
  # Database
  cloud_firestore: ^1.0.1
  # Cloud storage
  firebase_storage: ^8.0.0
  # User Auth
  # Social Auth
  # google_sign_in: ^4.5.9
  google_sign_in: ^5.0.0
  # Performance and metrics
  # User Auth
  firebase_auth: ^1.0.1
  firebase_analytics: ^7.0.1
  firebase_crashlytics: '^1.0.0'
  firebase_performance: ^0.6.0

  ## Other ##
  # State management
  provider: ^4.3.3
  # Data validator
  validators: ^2.0.0
  # Image and camera
  image_cropper: ^1.4.0
  image_picker: ^0.7.2+1

  url_launcher: ^6.0.2
  # url_launcher: ^5.7.10
  android_intent: ^2.0.0


  ## UI elements ##
  # Social sign in buttons
  # TODO consider to remove this if we want to use our own style. There might be some rules on how the sign in button should look
  flutter_signin_button: ^1.1.0
  # Date timeline
  date_picker_timeline: ^1.2.1
  # DateTime picker
  flutter_datetime_picker: ^1.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  carousel_slider: ^2.2.1

  fa_stepper: ^0.0.2

dev_dependencies:
  integration_test: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0 # Version check, null safety problems
  cloud_firestore_mocks: '>0.4.0'
  firebase_auth_mocks: '^0.6.0'
  google_sign_in_mocks: '^0.2.0'

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

  flutter_driver:
    sdk: flutter
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/ui/assets/logo_2.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # fonts:
  #   - family: AppIcons
  #     fonts:
  #       - asset: fonts/AppIcons.ttf  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
