import 'package:app/ui/shared/buttons/button.dart';
import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class FiltersForEventView extends StatefulWidget {
  FiltersForEventView({Key key}) : super(key: key);

  @override
  _FiltersForEventState createState() => _FiltersForEventState();
}

class _FiltersForEventState extends State<FiltersForEventView> {
  RangeValues _currentDaysValues = const RangeValues(0, 20);
  RangeValues _currentWeightValues = const RangeValues(0, 20);

  bool showYamaGeneratedPacklists = false;

  AppLocalizations texts;

  int _value = 1; // TO BE DELETED

  Widget _buildOpenSpotsSlider() {
    return RangeSlider(
        values: _currentDaysValues,
        min: 0,
        max: 20,
        labels: RangeLabels(
          _currentDaysValues.start.round().toString(),
          _currentDaysValues.end.round().toString(),
        ),
        onChanged: (RangeValues values) {
          setState(() {
            _currentDaysValues = values;
          });
        });
  }

  Widget _buildDaysSlider() {
    return RangeSlider(
        values: _currentWeightValues,
        min: 0,
        max: 20,
        labels: RangeLabels(
          _currentWeightValues.start.round().toString(),
          _currentWeightValues.end.round().toString(),
        ),
        onChanged: (RangeValues values) {
          setState(() {
            _currentWeightValues = values;
          });
        });
  }

  Widget _buildDivider() {
    return Divider(
      color: Colors.grey,
      height: 1.5,
    );
  }

  Widget _checkBoxMyEvents() {
    return Row(
      children: [
        Material(
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(
                  color: showYamaGeneratedPacklists == true
                      ? Colors.blue
                      : Colors.black,
                  width: 2.3),
            ),
            width: 20,
            height: 20,
            margin: EdgeInsets.fromLTRB(30, 10, 10, 10),
            child: Theme(
              data: ThemeData(unselectedWidgetColor: Colors.white),
              child: Checkbox(
                value: showYamaGeneratedPacklists,
                key: Key('filter_checkbox'),
                onChanged: (bool value) {
                  setState(
                    () {
                      showYamaGeneratedPacklists = value;
                    },
                  );
                },
                checkColor: Colors.blue,
                activeColor: Colors.transparent,
              ),
            ),
          ),
        ),
        RichText(
            text: TextSpan(
          children: [
            TextSpan(
              text: "Only show events generated by me ",
              style: new TextStyle(color: Colors.black),
            ),
          ],
        )),
      ],
    );
  }

  Widget _checkBoxUserEvents() {
    return Row(
      children: [
        Material(
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(
                  color: showYamaGeneratedPacklists == true
                      ? Colors.blue
                      : Colors.black,
                  width: 2.3),
            ),
            width: 20,
            height: 20,
            margin: EdgeInsets.fromLTRB(30, 10, 10, 10),
            child: Theme(
              data: ThemeData(unselectedWidgetColor: Colors.white),
              child: Checkbox(
                value: showYamaGeneratedPacklists,
                key: Key('filter_checkbox'),
                onChanged: (bool value) {
                  setState(
                    () {
                      showYamaGeneratedPacklists = value;
                    },
                  );
                },
                checkColor: Colors.blue,
                activeColor: Colors.transparent,
              ),
            ),
          ),
        ),
        RichText(
            text: TextSpan(
          children: [
            TextSpan(
              text: "Only show User generated events ",
              style: new TextStyle(color: Colors.black),
            ),
          ],
        )),
      ],
    );
  }

  Widget _checkBoxYamaEvents() {
    return Row(
      children: [
        Material(
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(
                  color: showYamaGeneratedPacklists == true
                      ? Colors.blue
                      : Colors.black,
                  width: 2.3),
            ),
            width: 20,
            height: 20,
            margin: EdgeInsets.fromLTRB(30, 10, 10, 10),
            child: Theme(
              data: ThemeData(unselectedWidgetColor: Colors.white),
              child: Checkbox(
                value: showYamaGeneratedPacklists,
                key: Key('filter_checkbox'),
                onChanged: (bool value) {
                  setState(
                    () {
                      showYamaGeneratedPacklists = value;
                    },
                  );
                },
                checkColor: Colors.blue,
                activeColor: Colors.transparent,
              ),
            ),
          ),
        ),
        RichText(
            text: TextSpan(
          children: [
            TextSpan(
              text: "Only show Yama generated events ",
              style: new TextStyle(color: Colors.black),
            ),
          ],
        )),
      ],
    );
  }

  Widget _buildClearFiltersButton() {
    var texts = AppLocalizations.of(context);

    return Button(
      onPressed: () =>
          Navigator.of(context).pop(), // TODO MAKE THIS TO CLEAR THE FILTERS
      label: texts.clearFilters,
      //backgroundColor: Colors.red TODO Uncomment when other branch is merged.
      height: 35,
    );
  }

  @override
  Widget build(BuildContext context) {
    var texts = AppLocalizations.of(context);

    return Scaffold(
      appBar: AppBar(
        leadingWidth: 100,
        leading: Container(
          child: TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: Text(
              texts.cancel,
              style: TextStyle(color: Colors.grey),
            ),
          ),
        ),
        title: Text(texts.packlistFilters + " STATIC",
            style: TextStyle(color: Colors.black, fontSize: 17)),
        actions: <Widget>[
          Padding(
            padding: EdgeInsets.only(right: 20.0),
            child: TextButton(
              onPressed: () {
                Navigator.pushNamed(context, '/packList');
              },
              child: Text(texts.apply),
            ),
          ),
        ],
      ),
      body: ListView(
        children: [
          SizedBox(
            height: 20,
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(
              "Open spots",
              style: Theme.of(context).textTheme.headline3,
            ),
          ),
          SliderTheme(
              data:
                  SliderThemeData(), // TODO GET TICK / CURRENT VALUE TO SHOW HERE UI
              child: _buildOpenSpotsSlider()),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(
              "Days",
              style: Theme.of(context).textTheme.headline3,
            ),
          ),
          SliderTheme(
              data:
                  SliderThemeData(), // TODO GET TICK / CURRENT VALUE TO SHOW HERE UI
              child: _buildDaysSlider()),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(
              texts.category,
              style: Theme.of(context).textTheme.headline3,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Wrap(
                  // TODO THIS IS WHAT WE SHOULD BE DOING!!!!!!!!!!!! SOMEHOW :) https://api.flutter.dev/flutter/material/ChoiceChip-class.html
                  children: List<Widget>.generate(
                    3,
                    (int index) {
                      return ChoiceChip(
                        backgroundColor: Colors.white,
                        label: Text('Item $index'),
                        selected: _value == index,
                        onSelected: (bool selected) {
                          setState(() {
                            _value = selected ? index : null;
                          });
                        },
                      );
                    },
                  ).toList(),
                ),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(
              "Country",
              style: Theme.of(context).textTheme.headline3,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(
              "Region",
              style: Theme.of(context).textTheme.headline3,
            ),
          ),
          _buildDivider(),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(
              texts.additionals,
              style: Theme.of(context).textTheme.headline3,
            ),
          ),
          _checkBoxMyEvents(),
          _checkBoxUserEvents(),
          _checkBoxYamaEvents(),
          Padding(
            padding: const EdgeInsets.fromLTRB(130, 20, 130, 0),
            child: _buildClearFiltersButton(),
          ),
        ],
      ),
    );
  }
}
