import 'package:app/constants/constants.dart';
import 'package:app/ui/shared/buttons/button.dart';
import 'package:app/ui/shared/form_fields/country_dropdown.dart';
import 'package:app/ui/shared/form_fields/custom_range_slider.dart';
import 'package:app/ui/shared/form_fields/region_dropdown.dart';
import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class FiltersForEventView extends StatefulWidget {
  FiltersForEventView({Key key}) : super(key: key);

  @override
  _FiltersForEventState createState() => _FiltersForEventState();
}

class _FiltersForEventState extends State<FiltersForEventView> {
  // Fields for sliders
  RangeValues _currentOpenSpotsValues = const RangeValues(0, 20);
  RangeValues _currentDaysValues = const RangeValues(1, 5);
  // Fields for country dropdown
  final GlobalKey<FormFieldState> _regionKey = GlobalKey<FormFieldState>();
  String country;
  String region;
  List<String> currentRegions = ['Choose country'];

  bool showMeGeneratedEvents = false;
  bool showUserGeneratedEvents = false;
  bool showYamaGeneratedEvents = false;

  AppLocalizations texts;

  int _value;
  List<String> _categories = [
    'Hike',
    'Snow Hike',
    'Fastpacking',
    'Ski',
    'Run',
    'Popup',
    'UL 101',
    'MYOG Workshop',
    'Repair Workshop'
  ];
  List<bool> _selectedCategories = [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ];

  Widget _buildOpenSpotsSlider() {
    return CustomRangeSlider(
      min: 0,
      max: 20,
      rangeValues: _currentOpenSpotsValues,
      onChanged: (RangeValues values) {
        setState(() => _currentOpenSpotsValues = values);
      },
    );
  }

  Widget _buildDaysSlider() {
    return CustomRangeSlider(
      min: 1,
      max: 5,
      rangeValues: _currentDaysValues,
      onChanged: (RangeValues values) {
        setState(() => _currentDaysValues = values);
      },
    );
  }

  List<Widget> _buildCategoriesSelector() {
    List<Widget> chips = [];

    for (int i = 0; i < _categories.length; i++) {
      FilterChip filterChip = FilterChip(
        showCheckmark: false,
        backgroundColor: Theme.of(context).scaffoldBackgroundColor,
        selectedColor: Theme.of(context).scaffoldBackgroundColor,
        label: Text(
          _categories[i],
          style: TextStyle(
              color: _selectedCategories[i] ? Colors.blue : Color(0xFF818181)),
        ),
        labelStyle: TextStyle(
          fontWeight: FontWeight.w400,
        ),
        selected: _selectedCategories[i],
        onSelected: (bool selected) {
          setState(() {
            _selectedCategories[i] = selected;
          });
        },
      );
      chips.add(filterChip);
    }
    return chips;
  }

  Widget _buildCountryDropdown() {
    return CountryDropdown(
      hint: "Country",
      onChanged: (value) {
        setState(() {
          _regionKey.currentState.reset();
          currentRegions = countryRegions[value];
        });
      },
    );
  }

  Widget _buildRegionDropdown() {
    return RegionDropdown(
      regionKey: _regionKey,
      hint: "Region",
      currentRegions: currentRegions,
    );
  }

  Widget _buildDivider() {
    return Divider(
      color: Colors.grey,
      height: 1.5,
    );
  }

  Widget _checkBoxMyEvents() {
    return Row(
      children: [
        Material(
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(
                  color: showMeGeneratedEvents == true
                      ? Colors.blue
                      : Colors.black,
                  width: 2.3),
            ),
            width: 20,
            height: 20,
            margin: EdgeInsets.fromLTRB(10, 10, 10, 10),
            child: Theme(
              data: ThemeData(unselectedWidgetColor: Colors.white),
              child: Checkbox(
                value: showMeGeneratedEvents,
                key: Key('filter_checkbox'),
                onChanged: (bool value) {
                  setState(
                    () {
                      showMeGeneratedEvents = value;
                    },
                  );
                },
                checkColor: Colors.blue,
                activeColor: Colors.transparent,
              ),
            ),
          ),
        ),
        RichText(
            text: TextSpan(
          children: [
            TextSpan(
                text: "Only show events generated by me ",
                style: Theme.of(context).textTheme.bodyText1),
          ],
        )),
      ],
    );
  }

  Widget _checkBoxUserEvents() {
    return Row(
      children: [
        Material(
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(
                  color: showUserGeneratedEvents == true
                      ? Colors.blue
                      : Colors.black,
                  width: 2.3),
            ),
            width: 20,
            height: 20,
            margin: EdgeInsets.fromLTRB(10, 10, 10, 10),
            child: Theme(
              data: ThemeData(unselectedWidgetColor: Colors.white),
              child: Checkbox(
                value: showUserGeneratedEvents,
                key: Key('filter_checkbox'),
                onChanged: (bool value) {
                  setState(
                    () {
                      showUserGeneratedEvents = value;
                    },
                  );
                },
                checkColor: Colors.blue,
                activeColor: Colors.transparent,
              ),
            ),
          ),
        ),
        RichText(
          text: TextSpan(
            children: [
              TextSpan(
                  text: "Only show User generated events",
                  style: Theme.of(context).textTheme.bodyText1),
            ],
          ),
        ),
      ],
    );
  }

  Widget _checkBoxYamaEvents() {
    return Row(
      children: [
        Material(
          child: Container(
            decoration: BoxDecoration(
              border: Border.all(
                  color: showYamaGeneratedEvents == true
                      ? Colors.blue
                      : Colors.black,
                  width: 2.3),
            ),
            width: 20,
            height: 20,
            margin: EdgeInsets.fromLTRB(10, 10, 10, 10),
            child: Theme(
              data: ThemeData(unselectedWidgetColor: Colors.white),
              child: Checkbox(
                value: showYamaGeneratedEvents,
                key: Key('filter_checkbox'),
                onChanged: (bool value) {
                  setState(
                    () {
                      showYamaGeneratedEvents = value;
                    },
                  );
                },
                checkColor: Colors.blue,
                activeColor: Colors.transparent,
              ),
            ),
          ),
        ),
        RichText(
          text: TextSpan(
            children: [
              TextSpan(
                  text: "Only show Yamatomichi generated events",
                  style: Theme.of(context).textTheme.bodyText1),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildClearFiltersButton() {
    var texts = AppLocalizations.of(context);

    return Button(
      onPressed: () =>
          Navigator.of(context).pop(), // TODO MAKE THIS TO CLEAR THE FILTERS
      label: texts.clearFilters,
      backgroundColor: Colors.red,
      height: 35,
    );
  }

  @override
  Widget build(BuildContext context) {
    var texts = AppLocalizations.of(context);

    return Scaffold(
      appBar: AppBar(
        leadingWidth: 100,
        leading: Container(
          child: TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: Text(
              texts.cancel,
              style: TextStyle(color: Colors.grey),
            ),
          ),
        ),
        title: Text(texts.filtersForEvents + " STATIC",
            style: TextStyle(color: Colors.black, fontSize: 17)),
        actions: <Widget>[
          Padding(
            padding: EdgeInsets.only(right: 20.0),
            child: TextButton(
              onPressed: () {
                Navigator.pushNamed(context, '/calendar');
              },
              child: Text(texts.apply),
            ),
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: ListView(
          children: [
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                texts.openSpots,
                style: Theme.of(context).textTheme.headline3,
              ),
            ),
            Padding(
              padding: const EdgeInsets.fromLTRB(8, 0, 8, 0),
              child: _buildOpenSpotsSlider(),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                texts.amountOfDays,
                style: Theme.of(context).textTheme.headline3,
              ),
            ),
            Padding(
              padding: const EdgeInsets.fromLTRB(8, 0, 8, 0),
              child: _buildDaysSlider(),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                texts.category,
                style: Theme.of(context).textTheme.headline3,
              ),
            ),
            Wrap(
              direction: Axis.horizontal,
              spacing: 6.0,
              runSpacing: 6.0,
              children: _buildCategoriesSelector(),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                texts.country,
                style: Theme.of(context).textTheme.headline3,
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: _buildCountryDropdown(),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                texts.region,
                style: Theme.of(context).textTheme.headline3,
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: _buildRegionDropdown(),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: _buildDivider(),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                texts.additionals,
                style: Theme.of(context).textTheme.headline3,
              ),
            ),
            _checkBoxMyEvents(),
            _checkBoxUserEvents(),
            _checkBoxYamaEvents(),
            Padding(
              padding: const EdgeInsets.fromLTRB(110, 20, 110, 0),
              child: _buildClearFiltersButton(),
            ),
          ],
        ),
      ),
    );
  }
}
