/// Flutter icons YamaIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YamaIcons
///      fonts:
///       - asset: fonts/YamaIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class YamaIcons {
  YamaIcons._();

  static const _kFontFam = 'YamaIcons';
  static const String _kFontPkg = null;

  static const IconData yama_y = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
